;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-append-line
        evil-backward-char
        evil-backward-word-begin
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-end-of-line
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-previous-line
        go-mode-insert-and-indent
        keyboard-quit
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        evil-goto-first-line
        evil-goto-line
        evil-inner-tag
        evil-mouse-drag-region
        evil-normal-state
        evil-scroll-page-down
        evil-scroll-page-up
        evil-search-forward
        evil-search-next
        evil-search-previous
        evil-visual-line
        evil-window-middle
        handle-switch-frame
        helm-confirm-and-exit-minibuffer
        isearch-abort
        isearch-exit
        isearch-printing-char
        my-helm
        ns-handle-scroll-bar-event
        ))
