;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-star
        ess-smart-comma
        evil-append
        evil-append-line
        evil-backward-WORD-begin
        evil-backward-char
        evil-backward-word-begin
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-end-of-line
        evil-exit-visual-state
        evil-force-normal-state
        evil-forward-WORD-begin
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-open-below
        evil-previous-line
        evil-ret
        go-mode-insert-and-indent
        keyboard-quit
        sp--self-insert-command
        vr/replace
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        evil-a-curly
        evil-ace-jump-word-mode
        evil-ex
        evil-goto-first-line
        evil-goto-line
        evil-inner-tag
        evil-mouse-drag-region
        evil-normal-state
        evil-scroll-page-down
        evil-scroll-page-up
        evil-search-forward
        evil-search-next
        evil-search-previous
        evil-substitute
        evil-visual-char
        evil-visual-line
        evil-window-middle
        evil-window-prev
        handle-switch-frame
        helm-M-x
        helm-confirm-and-exit-minibuffer
        isearch-abort
        isearch-delete-char
        isearch-exit
        isearch-printing-char
        last-buffer
        my-helm
        ns-handle-scroll-bar-event
        term-send-raw
        ))
