;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-backward-word-begin
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-end-of-line
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-previous-line
        keyboard-quit
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        evil-mouse-drag-region
        evil-normal-state
        evil-scroll-page-down
        evil-scroll-page-up
        evil-window-middle
        helm-confirm-and-exit-minibuffer
        my-helm
        ns-handle-scroll-bar-event
        ))
